version: '3.7'

networks:
  sql-net:
    name: sql-net
    driver: bridge

services:
    sqlserver1:
        build: 
          context: .
          dockerfile: dockerfile
        ports:  
          - "15789:1433"
        env_file:
          - server.env
          - pwd.env
        networks:
          - sql-net

  #IF you want to persist data uncomment those lines
        #volumes: 
         # - sqlsystem:/var/opt/mssql/
          #- sqldata:/var/opt/sqlserver/data
          #- sqllog:/var/opt/sqlserver/log
          #- sqlbackup:/var/opt/sqlserver/backup

#volumes:
 # sqlsystem:
  #sqldata:
  #sqllog:
  #sqlbackup: